### ISSUE TITLE
Mob spawners do not take damage

### ISSUE THREAD

**Issue by ItsHarry** [drtshock/ObsidianDestroyer#28]
Added mob spawners to the configuration, durability displays correctly when left-clicking using a Potato.

However, after blowing up TNT next to it, the durability does not change. Obsidian durability does change.

No error in console. Is this intended behavior or a bug?

**Comment by drtshock** [comment]
Can you put your materials.yml in a gist please.

**Comment by ItsHarry** [comment]
```yml
      Minecarts: true
  MOB_SPAWNER:
    BlastRadius: 2
    Durability:
      Amount: 7
      FluidDamper: 0.07
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: true
      ResetAfter: 600000
    EnabledFor:
      TNT: true
      Creepers: true
      Ghasts: true
      Cannons: true
      Withers: true
      Minecarts: true
  ENCHANTMENT_TABLE:
```

I haven't really touched the materials.yml, this is all I added. Again, the durability displays when I left-click the mob spawner using a Potato, which indicates that the materials.yml is correctly configured.
