### ISSUE TITLE
Need help with fences

### ISSUE THREAD

**Issue by HunterGPlays** [drtshock/ObsidianDestroyer#38]
I can't figure out how to make fences act like a solid block. The plugin works fine with obsidian but when it comes to fences, it doesn't work. I want them to blow up when someone lights TNT in water right next to it (with sand of course). Any help? I know loads of other servers do this using ObsidianDestroyer.

**Comment by HunterGPlays** [comment]
This is how I configured it:

```
  FENCE:
    BlastRadius: 4
    Destructible: true
    Durability:
      Amount: 1
      FluidDamper: 0
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: false
      ResetAfter: 600000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: true
      Withers: false
      Minecarts: false
```
