### ISSUE TITLE
Factions Hooking not working

### ISSUE THREAD

**Issue by Ferocimo** [drtshock/ObsidianDestroyer#88]
Hello,

We recently bought your plugin and are loving the customization possibilities it offers. However, one main thing we wanted in your plugin was the Factions hooking, which does not seem to work on our server.

We want the durability of obsidian to be tripled when all members of a faction are offline. We set up the config as follows :

```
# Works directly with Factions for extended event processing; adds the ability
#  for durability multipliers based on the online status of a faction.
# Works with most versions of Factions
Factions:
  # Enable Hooking - enabling will allow obsidian destroyer to pass interactions directly to factions.
  Enabled: true
  # Toggles explosion features between ObsidianDestroyer and Factions.
  HandleExplosions: true

  # Enable this to only damage blocks when Faction power is low
  UseFactionPowerLevel: false

  # Toggle to manage an offline faction. (Override & Multiplier)
  # Enables an override that will allow [managed] blocks to be destroyed for a protected offline faction.
  HandleOffline: true
  # Protect factions that offline instead of applying damage
  ProtectOffline: false
  # Multiplier to use for changing the durability of an offline faction.
  OfflineDurabilityMultiplier: 3.0
  # Toggle to manage an online faction. (Multiplier)
  HandleOnline: false
  # Multiplier to use for changing the durability of an online faction.
  OnlineDurabilityMultiplier: 1.0
```

We're using this plugin : 
https://www.spigotmc.org/resources/factions3-for-1-13.63602/
In latest version, 3.3.0.

Could you please help us ? We have to reopen our server in two weeks, and we would like this functionnality to be operationnal...

Thank you
